<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="unittest-failure"
    errors="0" failures="1" hostname="" id="" package="unittest-failure" skipped="0"
    tests="1" time="0.000" timestamp="">
  
    <testcase name="demoTest" classname="unittest-failure" time="0.000" assertions="0"><failure message="AssertionError [ERR_ASSERTION]: 1 == 0 - expected &#34;0&#34; but got: &#34;1&#34;">    at Object.demoTest (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/test/asynchookstests/unittest-failure/unittest-failure.js:5:12)
    at Context.callAsync (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/context.js:218:20)
    at Context.invokeMethod (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/context.js:264:21)
    at Promise (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/hooks/_basehook.js:75:24)
    at new Promise (&lt;anonymous&gt;)
    at UnitTest.run (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/hooks/_basehook.js:50:14)
    at TestCase.runUnitTest (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testcase.js:64:21)
    at TestCase.run (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testcase.js:47:23)
    at Runnable.handleRunnable [as __runFn] (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:349:32)
    at Runnable.run (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/runnable.js:123:21)
    at TestSuite.createRunnable (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:416:33)
    at TestSuite.handleRunnable (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:420:17)
    at createSession.then.then._ (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:348:21)</failure>
    </testcase>
  

  

  
  </testsuite>
</testsuites>
